name: Build and Deploy Docs - Preview

on:
  pull_request:

permissions:
  contents: write

env:
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/docs-build-artifact.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-upload
    environment:
      name: github-pages-preview/${{ github.event.number }}
      url: https://${{ github.repository_owner }}.github.io/${{github.event.repository.name}}/preview/${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - uses: actions/download-artifact@v4

      - name: Add/Update Preview
        run: |
          mkdir -p preview
          rm -rf preview/${{ github.event.number }}
          mv artifact preview/${{ github.event.number }}

      - name: Commit and Push
        run: |
          git add --all preview/${{ github.event.number }}
          git clean -fdx
          git commit \
            -m "Preview for PR#${{ github.event.number }}" \
            -m "${{ github.event.pull_request.head.sha }}"
          git push
