name: Docs - PR Cleanup

on:
  pull_request:
    types: [closed]

env:
  GIT_COMMITTER_NAME: github-actions[bot]
  GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com

concurrency:
  group: "pages-pr"
  cancel-in-progress: true

jobs:
  remove-preview-files:
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.commit.outputs.hash }}
    permissions:
      contents: write
    concurrency:
      group: deploy
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Remove Preview
        run: |
          git rm -rf pr/${{ github.event.number }}

      - name: Commit and Push
        id: commit
        run: |
          git commit \
            -m "Remove Preview for PR#${{ github.event.number }}" \
            -m "${{ github.event.pull_request.head.sha }}"
          git push
          echo "hash=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

  comment-closed:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: remove-preview-files
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            Preview removed on merge/PR close with ${{ needs.remove-preview-files.outputs.hash }}
